development:
  dialect: postgres
  datasource: dbname=beaker_dev sslmode=disable host=localhost user=postgres password=password  
  dir: db-migrations
  table: migrations

test:
  dialect: postgres
  datasource: dbname=beaker_test sslmode=disable host=localhost user=postgres password=password 
  dir: db-migrations
  table: migrations

production:
  dialect: postgres
  datasource: dbname=beaker_prod sslmode=disable host=localhost user=postgres password=password 
  dir: db-migrations
  table: migrations