name: PR CI

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DB_URL: postgres://postgres:password@localhost:5432/postgres?sslmode=disable
      DB_ENV: test
      NEW_RELIC_API_KEY: dummy-key
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.1'
      - name: Install Docker
        uses: docker/setup-buildx-action@v3
      - name: Install Docker Compose
        run: |
          sudo apt-get update -y
          sudo apt-get install -y docker-compose
      - name: Run setup
        run: make setup
      - name: Run post_create_command.sh
        run: ./post_create_command.sh
      - name: Recreate DB, build, test, lint, and integration tests
        run: |
          make bootstrap
          DB_ENV=development make recreate-db build
          DB_ENV=test make recreate-db test lint
